title: International Press journal JBR author support
description: TeX related material for the manuscript preparation for the
             International Press Journal of Blockchain Research
             (JBR)
show_downloads: true
theme: jekyll-theme-tactile
